line-length = 120
src = ["netcontrol", "templates", "Firewall_converter", "tests"]
target-version = "py311"

[lint]
select = ["E", "F", "I", "UP", "ASYNC"]
ignore = []

[lint.isort]
combine-as-imports = true
force-single-line = false
